#!/usr/bin/env python3
# Copyright (c) 2026 Bruce Blay
# SPDX-License-Identifier: GPL-3.0-or-later
"""Convert mono 16-bit PCM WAV loops into src/Samples.h.

Usage: tools/embed_samples.py water.wav rain.wav wind.wav

Each input must already be mono 16-bit PCM at field::rate (32000 Hz); this
tool does not resample or downmix. Source recordings and their licenses are
tracked in docs/SOURCES.md, not in this repository -- see that file before
replacing a placeholder clip.
"""
import argparse
import struct
import sys
import wave
from pathlib import Path


def read_pcm16_mono(path: Path):
    with wave.open(str(path), 'rb') as w:
        if w.getsampwidth() != 2:
            raise SystemExit(f'{path}: expected 16-bit PCM, got {w.getsampwidth()*8}-bit')
        if w.getnchannels() != 1:
            raise SystemExit(f'{path}: expected mono, got {w.getnchannels()} channels')
        if w.getframerate() != 32000:
            raise SystemExit(f'{path}: expected 32000 Hz, got {w.getframerate()} Hz')
        frames = w.readframes(w.getnframes())
    return struct.unpack(f'<{len(frames)//2}h', frames)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('wavs', nargs='+', type=Path)
    parser.add_argument('-o', '--output', type=Path, default=Path(__file__).resolve().parents[1] / 'src' / 'Samples.h')
    args = parser.parse_args()

    clips = []
    for path in args.wavs:
        name = path.stem
        samples = read_pcm16_mono(path)
        clips.append((name, samples))
        print(f'{name}: {len(samples)} samples, {len(samples)/32000:.2f}s, {len(samples)*2} bytes', file=sys.stderr)

    total_bytes = sum(len(s) * 2 for _, s in clips)
    print(f'total: {total_bytes} bytes ({total_bytes/1024/1024:.2f} MiB)', file=sys.stderr)

    with open(args.output, 'w') as out:
        out.write('// Copyright (c) 2026 Bruce Blay\n')
        out.write('// SPDX-License-Identifier: GPL-3.0-or-later\n')
        out.write('#pragma once\n#include <cstdint>\n\n')
        out.write('#ifndef PROGMEM\n#define PROGMEM\n#endif\n\n')
        out.write('// Generated by tools/embed_samples.py -- do not hand-edit.\n')
        out.write('// Source recordings and licenses: see docs/SOURCES.md.\n')
        out.write('namespace samples {\n\n')
        for name, data in clips:
            out.write(f'static const int16_t {name}[{len(data)}] PROGMEM = {{\n')
            for i in range(0, len(data), 20):
                out.write(','.join(str(v) for v in data[i:i+20]))
                out.write(',\n')
            out.write('};\n\n')
        out.write('struct Clip { const int16_t* data; uint32_t length; };\n')
        out.write('static const Clip textures[] = {\n')
        for name, data in clips:
            out.write(f'  {{{name}, {len(data)}}},\n')
        out.write('};\n')
        out.write('}\n')


if __name__ == '__main__':
    main()
